name: Scrobbler
on:
  schedule:
    - cron: "* * * * *"
jobs:
  scrobbler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: LastFM
      run: |
        pip install requests
        year=`date +"%Y"`
        month=`date +"%m"`
        if [ ! -d "$PWD/$year" ]; then
          mkdir $PWD/$year
        fi
        if [ ! -d "$PWD/$year/$month" ]; then
          mkdir $PWD/$year/$month
        fi
        python lastfm.py -k ${{ secrets.LASTFM_APIKEY }} -u ${{ secrets.LASTFM_USER }} -s -p $PWD
        #sleep 60
    - name: Commit Files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add music
        gstatus=`git status music | grep 'nothing to commit, working tree clean'`
        if [[ `git status --porcelain --untracked-files=no` ]]; then
          echo "Hay cambios"
          #date=`date +"%Y-%m-%d %H:%M"`
          #git commit -m 'Lastfm: $date'
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
