name: Scrobbler

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scrobbler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: LastFM
      run: |
        pip install requests
        year=`date +"%Y"`
        month=`date +"%m"`
        if [ ! -d "$PWD/$year" ]; then
          mkdir $PWD/$year
        fi
        if [ ! -d "$PWD/$year/$month" ]; then
          mkdir $PWD/$year/$month
        fi
        python lastfm.py -k $LASTFM_APIKEY -u $LASTFM_USER -s -p $PWD > tmp
        sleep 60
        python lastfm.py -k $LASTFM_APIKEY -u $LASTFM_USER -s -p $PWD > tmp
        sleep 60
        python lastfm.py -k $LASTFM_APIKEY -u $LASTFM_USER -s -p $PWD > tmp
        sleep 60
        python lastfm.py -k $LASTFM_APIKEY -u $LASTFM_USER -s -p $PWD > tmp
    - name: Commit Files
      run: |
        date=`date +"%Y-%m-%d %H:%M"`
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        if [ -f tmp ]; then
          git add music
          git commit -m "Lastfm: $date" -a
          rm tmp
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    env:
      LASTFM_APIKEY: ${{ secrets.LASTFM_APIKEY }}
      LASTFM_USER: ${{ secrets.LASTFM_USER }}
