name: Scrobbler

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  scrobbler:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: LastFM
      run: |
        pip install requests
        year=`date +"%Y"`
        month=`date +"%m"`
        if [ ! -d "$PWD/$year" ]; then
          mkdir $PWD/$year
        fi
        if [ ! -d "$PWD/$year/$month" ]; then
          mkdir $PWD/$year/$month
        fi
        python lastfm.py -k $LASTFM_APIKEY -u $LASTFM_USER -s -p $PWD
    env:
      LASTFM_APIKEY: ${{ secrets.LASTFM_APIKEY }}
      LASTFM_USER: ${{ secrets.LASTFM_USER }}
