name: Songs Scrobbler
on:
  schedule:
#    - cron: "15 * * * *"
    - cron: "30 * * * *"
jobs:
  scrobbling:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: LastFM & Commits
      run: |
        echo "Config Github"
        git config --local user.email ${{ secrets.COMMIT_EMAIL }}
        git config --local user.name "Jorge Hernández"
        git config --local pull.rebase true
        echo "Scrobbling all items:"
        sudo apt-get install python3-pip
        python3 -m pip install python-dateutil
        python3 -m pip install requests
        python3 lastfm.py -k ${{ secrets.LASTFM_APIKEY }} -u ${{ secrets.LASTFM_USER }} -t -p $PWD
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
